user www-data;
worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    sendfile on;
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/css application/javascript application/json;

    server {
        listen 80;
        server_name localhost;

        # Normalize the repeated slash introduced by 2p's existing proxy_pass.
        # uwsgi_params supplies normalized $document_uri as PATH_INFO.
        merge_slashes on;
        location /nzgd {
            include /etc/nginx/uwsgi_params;
            uwsgi_pass unix:/tmp/nzgd.sock;
            uwsgi_param SCRIPT_NAME /nzgd;
        }

        location / {
            return 404;
        }
    }
}
